apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-auth
  labels: 
    app: i27-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-auth
  template:
    metadata:
      labels:
        app: i27-auth
    spec:
      containers:
        - name: i27-auth
          image: ${IMAGE}   # substituted at deploy time via envsubst, e.g. devopswithcloudhub/i27helpdesk-auth:<git-sha-tag>
          ports:
            - containerPort: 8081
          envFrom: 
          - secretRef:
              name: i27-auth-dev  # Secrets containing senesitive information like database username, password, jwt token secret, etc. are stored in Kubernetes secrets and mounted as environment variables in the container 
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 30   #  initial delay before the first probe is initiated when the container is started
            periodSeconds: 20          # how often (in seconds) to perform the probe
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30   #  initial delay before the first probe is initiated when the container is started
            periodSeconds: 30         # how often (in seconds) to perform the probe
          # resources:
          #   requests:
          #     memory: "64Mi"   # Minimum amount of memory required by the container
          #     cpu: "250m"      # Minimum amount of CPU required by the container
          #   limits:
          #     memory: "128Mi"  # Maximum amount of memory that can be used by the container
          #     cpu: "500m"      # Maximum amount of CPU that can be used by the container
