apiVersion: v1
kind: Service
metadata:
  name: i27-auth
  labels:
    app: i27-auth
spec:
  type: ClusterIP
  selector:
    app: i27-auth
  ports:
    - protocol: TCP
      port: 80              # Service port  
      targetPort: 8081      # Container port